# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_option_rightanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quixID',
            field=models.IntegerField(default='1'),
        ),
    ]
