# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_quixid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quixID',
            field=models.IntegerField(unique='1'),
        ),
    ]
